"""empty message

Revision ID: 722399b52a96
Revises: 52e1bdaec24b
Create Date: 2019-10-01 00:07:58.525302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '722399b52a96'
down_revision = '52e1bdaec24b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_venue', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'seeking_venue')
    # ### end Alembic commands ###
